# Practic session

In [1]:
# Import numpy library
import numpy as np

# creating an array using Numpy

# 1D Array

In [5]:

food= np.array(["samosa","pakora","raita"])
food

array(['samosa', 'pakora', 'raita'], dtype='<U6')

In [6]:
price= np.array([5,5,5])
price

array([5, 5, 5])

In [7]:
price.mean()

5.0

In [9]:
#onces
np.ones(4)

array([1., 1., 1., 1.])

In [10]:
#zeros
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [12]:
#empty
np.empty(4)

array([1., 1., 1., 1.])

In [13]:
#range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
#specify
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [15]:
np.arange(2,20,3)

array([ 2,  5,  8, 11, 14, 17])

In [16]:
#table of 5
np.arange(5,55,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [18]:
# line space
np.linspace(1,10,num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [19]:
#specfic data type
np.ones(50, dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int64)

In [20]:
np.ones(50, dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# Array Function

In [21]:
a = np.array([2,0.2,0.001,2.5,3,1,5,100,320,250,270])
a

array([2.0e+00, 2.0e-01, 1.0e-03, 2.5e+00, 3.0e+00, 1.0e+00, 5.0e+00,
       1.0e+02, 3.2e+02, 2.5e+02, 2.7e+02])

In [23]:
a.sort()
a

array([1.0e-03, 2.0e-01, 1.0e+00, 2.0e+00, 2.5e+00, 3.0e+00, 5.0e+00,
       1.0e+02, 2.5e+02, 2.7e+02, 3.2e+02])

# 2D arrays

In [38]:
x=np.array([[1,2],[9,8]])
x

array([[1, 2],
       [9, 8]])

In [39]:
y=np.array([[15,14],[11,13]])
y

array([[15, 14],
       [11, 13]])

In [40]:
c= np.concatenate((x,y), axis=0)
c

array([[ 1,  2],
       [ 9,  8],
       [15, 14],
       [11, 13]])

In [45]:
c.sort()
c

array([[ 1,  2],
       [ 8,  9],
       [14, 15],
       [11, 13]])

# 3D arrays


In [56]:
d =np.array([[[1,2,3,4,5],
            [5,6,7,8,9]],
            [[7,8,9,10],
            [11,12,13]],
            [[1,3,4,5],
            [12,16,17]]])


C:\Users\UMAR\AppData\Local\Temp\ipykernel_3832\1880255676.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  d =np.array([[[1,2,3,4,5],


In [54]:
d

array([[list([1, 2, 3, 4, 5]), list([5, 6, 7, 8, 9])],
       [list([7, 8, 9, 10]), list([11, 12, 13])],
       [list([1, 3, 4, 5]), list([12, 16, 17])]], dtype=object)

In [57]:
a=np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [59]:
#reshape
a=a.reshape(3,3) # 3*3=9
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])