In [ ]:
#numpy basic

In [2]:
import numpy as np
a=np.array([5,5,5,5,5,5,5])

In [3]:
a

array([5, 5, 5, 5, 5, 5, 5])

In [ ]:
#list of lists

In [7]:
b = np.array([[5,5,5],[5,5,5],[5,5,5]])
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [11]:
type(b)

numpy.ndarray

In [12]:
len(b)

3

In [14]:
b[0]

array([5, 5, 5])

In [17]:
b[0:3]

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [ ]:
#1D array


In [19]:
import numpy as np
a= np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [22]:
b=np.zeros(2)
b

array([0., 0.])

In [24]:
c=np.ones(3)
c

array([1., 1., 1.])

In [31]:
# create an array with 2 elements
d=np.empty(2)
d

array([0., 0.])

In [32]:
# with range of elements
e =np.arange(6)
e

array([0, 1, 2, 3, 4, 5])

In [34]:
# with specific range of elements
f = np.arange(2,20)
f

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [36]:
#continue...
g = np.arange(2,20,2)
g

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [38]:
# linerly spaced arrays
h=np.linspace(0,10,num=5)
h

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [39]:
# 3D array
#making and reshaping a 3D array 
i=np.arange(24).reshape(2,3,4)
i

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])