In [2]:
import numpy as np
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [3]:
b=np.zeros(2)
b

array([0., 0.])

In [4]:
c=np.ones(3)
c

array([1., 1., 1.])

In [6]:
d=np.empty(3)
d

array([1.17491536e-311, 6.06712613e-321, 2.03711596e-312])

In [4]:
# With the range of element 
e=np.arange(6)
e

array([0, 1, 2, 3, 4, 5])

In [5]:
#with the spasific range of element 
e=np.arange(2, 20)
e

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [6]:
# to be continue .....
e=np.arange(2, 20 ,2)
e

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])