# numpy practiec 


In [1]:
#import this library in J.notbook
import numpy as np


# Creating an array using Numpy

In [3]:
# 1D array
food=np.array(["samosa ","pakora","raita"])
food

array(['samosa ', 'pakora', 'raita'], dtype='<U7')

In [4]:
price=np.array([5,5,5])
price

array([5, 5, 5])

In [5]:
type(food)

numpy.ndarray

In [6]:
len(price)

3

In [7]:
food[0]

'samosa '

In [9]:
#ones
np.ones(3)

array([1., 1., 1.])

In [11]:
#empty
np.empty([5,5])

array([[6.23042070e-307, 1.86918699e-306, 1.69121096e-306,
        7.56599128e-307, 1.33511018e-306],
       [1.33511969e-306, 6.23037996e-307, 6.23053954e-307,
        9.34609790e-307, 8.45593934e-307],
       [9.34600963e-307, 1.20161594e-306, 9.34608432e-307,
        1.60221208e-306, 6.23059726e-307],
       [1.33511290e-306, 6.23059386e-307, 9.34608432e-307,
        9.34609790e-307, 1.37962117e-306],
       [1.60217812e-306, 1.42418987e-306, 1.42410974e-306,
        5.97819431e-322, 2.10081501e-312]])

In [12]:
#arange
np.arange(5)

array([0, 1, 2, 3, 4])

In [13]:
#specific Interval
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [14]:
#table of 5
np.arange(5,55,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])